### ISSUE TITLE
[BUG] VS Code IDE stops working with a grey screen ("GSOD")

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#891]
<img width="1506" alt="Screen Shot 2021-11-07 at 9 32 13 AM" src="https://user-images.githubusercontent.com/13432105/140651535-c6fdb722-4fbd-4941-8763-f2c3313a386a.png">

All IDE controls continue to work properly, but the WebView remains grey.

Not yet sure how to reproduce.

Does not appear to be related to a memory leak.   None of the code processes have high memory usage.

This bug was encountered on an aarch64 platform.

**Comment by davidnich** [comment]
another occurrence - from the unmerged drafts branch - so maybe already fixed in develop?:
```
ypeError: Cannot set property 'orig-config-items' of undefined
	at vscode-file://vscode-app/export/home2/dnichols/.vscode/extensions/qoretechnologies.qorus-vscode-2.4.0/out/extension.js:199746
	at Array.forEach (<anonymous>)
	at QorusProjectInterfaceInfo.setOrigConfigItems (vscode-file://vscode-app/export/home2/dnichols/.vscode/extensions/qoretechnologies.qorus-vscode-2.4.0/out/extension.js:199744)
	at vscode-file://vscode-app/export/home2/dnichols/.vscode/extensions/qoretechnologies.qorus-vscode-2.4.0/out/extension.js:204574
	at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at f.$onMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95)
	at n._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at n._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at n._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at n._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98
	at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113
	at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at f._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at w.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at Socket.m (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
```

**Comment by davidnich** [comment]
from develop while reproducing errors in config items in FSMs:
```
[[object Object]]Cannot read property 'config-items' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'config-items' of undefined
	at vscode-file://vscode-app/home/david/.vscode/extensions/qoretechnologies.qorus-vscode-2.3.25/out/extension.js:199296
	at Array.forEach (<anonymous>)
	at QorusProjectInterfaceInfo.setOrigConfigItems (vscode-file://vscode-app/home/david/.vscode/extensions/qoretechnologies.qorus-vscode-2.3.25/out/extension.js:199294)
	at vscode-file://vscode-app/home/david/.vscode/extensions/qoretechnologies.qorus-vscode-2.3.25/out/extension.js:204100
	at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at _.$onMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96)
	at t._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99)
	at t._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99)
	at t._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99)
	at t._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99
	at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114
	at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at r.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at n._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at w.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at Socket.T (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
  ERR o.logFailedRequest is not a function: TypeError: o.logFailedRequest is not a function
	at /home/david/.vscode/extensions/redhat.java-1.1.0/dist/extension.js:2:779142
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:93216)
```

**Comment by davidnich** [comment]
I believe this was fixed in 3.0

**Comment by davidnich** [comment]
still happening in 3.0.1: no relevant console messages or output messages

**Comment by davidnich** [comment]
right before the GSOD in FSMs, I get a dramatic slowdown in performance of the IDE
this time I got the following messages in the console right before the GSOD:
```
[Extension Host] SAVING DRAFT WITH THIS DATA step 57053cffeb0626a96ad99d816d3c5e80 Object
console.ts:137 [Extension Host] SAVING DRAFT WITH THIS DATA fsm Up1z_qYhfp Object
console.ts:137 [Extension Host] SAVING DRAFT WITH THIS DATA fsm Up1z_qYhfp Object
console.ts:137 [Extension Host] SAVING DRAFT WITH THIS DATA fsm Up1z_qYhfp Object
console.ts:137 [Extension Host] SAVING DRAFT WITH THIS DATA fsm Up1z_qYhfp Object
console.ts:137 [Extension Host] SAVING DRAFT WITH THIS DATA fsm Up1z_qYhfp Object
webview.bundle.js:1 Object Object
webview.bundle.js:1 Object
webview.bundle.js:1 Object
webview.bundle.js:1 null "any"
webview.bundle.js:1 false
webview.bundle.js:1 undefined true
webview.bundle.js:1 Object
webview.bundle.js:1 any any
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 Object
webview.bundle.js:1 any string
webview.bundle.js:1 false
webview.bundle.js:1 get-data completed BBM_GetData fsm undefined string
webview.bundle.js:1 string
webview.bundle.js:1 Object Object
```

**Comment by davidnich** [comment]
seems to happen while editing config item values in an FSM connector - may be related to the YAML validation on input

**Comment by davidnich** [comment]
this is fixed
